sudo: false
language: node_js
node_js:
  - 7
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - iojs
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release